// ============================================================
// GOAP Mission: Simple_Mission
// Mission Type : BASIC
// Variant: 1
// Generated by GOAP Mission Designer
// ============================================================

use crate::models::atomics::{Action, WorldState, GoalState};

// ============================================================
// MISSION STATES
// ============================================================

/// Initial world state
pub const INITIAL_STATE : WorldState = WorldState(0x0000000000000000);

/// Goal state
pub const GOAL_STATE  : GoalState  = GoalState (0x000000000000000F);

// ============================================================
// BIT FIELD CONSTANTS
// ============================================================

// POWER : 1-bit field  bits 0-0
pub const POWER_MASK                      : u64 = 0x0000000000000001;
pub const POWER_SHIFT                     : u64 = 0x0000000000000000;
pub const POWER_OFF                       : u64 = 0x0000000000000000;
pub const POWER_ON                        : u64 = 0x0000000000000001;

// SENSOR : 1-bit field  bits 1-1
pub const SENSOR_MASK                     : u64 = 0x0000000000000002;
pub const SENSOR_SHIFT                    : u64 = 0x0000000000000001;
pub const SENSOR_OFF                      : u64 = 0x0000000000000000;
pub const SENSOR_ON                       : u64 = 0x0000000000000002;

// DATA : 2-bit field  bits 2-3
pub const DATA_MASK                       : u64 = 0x000000000000000C;
pub const DATA_SHIFT                      : u64 = 0x0000000000000002;
pub const DATA_NONE                       : u64 = 0x0000000000000000;
pub const DATA_COLLECTING                 : u64 = 0x0000000000000004;
pub const DATA_READY                      : u64 = 0x0000000000000008;
pub const DATA_SENT                       : u64 = 0x000000000000000C;

// RESULT : 2-bit field  bits 4-5
pub const RESULT_MASK                     : u64 = 0x0000000000000030;
pub const RESULT_SHIFT                    : u64 = 0x0000000000000004;
pub const RESULT_NONE                     : u64 = 0x0000000000000000;
pub const RESULT_SUCCESS                  : u64 = 0x0000000000000010;
pub const RESULT_FAILED                   : u64 = 0x0000000000000020;
pub const RESULT_ABORTED                  : u64 = 0x0000000000000030;

// ============================================================
// ACTIONS  (5 total)
// ============================================================

pub const ACTIONS : [Action; 5] = [
    // Turn on system
    Action { name: "Power_On"              , pre_mask: 0x00000001, pre_value: 0x00000000, effect_mask: 0x00000001, effect_value: 0x00000001, cost:   1 },
    // Enable sensor
    Action { name: "Enable_Sensor"         , pre_mask: 0x00000003, pre_value: 0x00000001, effect_mask: 0x00000002, effect_value: 0x00000002, cost:   1 },
    // Start collecting
    Action { name: "Collect_Data"          , pre_mask: 0x00000003, pre_value: 0x00000003, effect_mask: 0x0000000C, effect_value: 0x00000004, cost:   5 },
    // Process collected data
    Action { name: "Process_Data"          , pre_mask: 0x0000000F, pre_value: 0x00000007, effect_mask: 0x0000000C, effect_value: 0x00000008, cost:   3 },
    // Transmit results
    Action { name: "Send_Data"             , pre_mask: 0x0000000F, pre_value: 0x0000000B, effect_mask: 0x0000000C, effect_value: 0x0000000C, cost:   2 },
];

/*
┌────────────────────────────────────────────────────────────────────┐
│  BIT LAYOUT  (6 bits used of 64 available)
├────────────────────────────────────────────────────────────────────┤
│  Bits  0- 0 : POWER        (1 bit )  [OFF, ON]
│  Bits  1- 1 : SENSOR       (1 bit )  [OFF, ON]
│  Bits  2- 3 : DATA         (2 bits)  [NONE, COLLECTING, READY, SENT]
│  Bits  4- 5 : RESULT       (2 bits)  [NONE, SUCCESS, FAILED, ABORTED]
└────────────────────────────────────────────────────────────────────┘
*/
