// ============================================================
// GOAP Mission: ELS_Full_Mission
// Mission Type : EMITTER_LOCALISATION
// Variant: 2
// Generated by GOAP Mission Designer
// ============================================================

use crate::models::atomics::{Action, WorldState, GoalState};

// ============================================================
// MISSION STATES
// ============================================================

/// Initial world state
pub const INITIAL_STATE : WorldState = WorldState(0x0000000000000000);

/// Goal state
pub const GOAL_STATE  : GoalState  = GoalState (0x0000000033C00005);

// ============================================================
// BIT FIELD CONSTANTS
// ============================================================

// POWER : 1-bit field  bits 0-0
pub const POWER_MASK                      : u64 = 0x0000000000000001;
pub const POWER_SHIFT                     : u64 = 0x0000000000000000;
pub const POWER_OFF                       : u64 = 0x0000000000000000;
pub const POWER_ON                        : u64 = 0x0000000000000001;

// SELF_TEST : 2-bit field  bits 1-2
pub const SELF_TEST_MASK                  : u64 = 0x0000000000000006;
pub const SELF_TEST_SHIFT                 : u64 = 0x0000000000000001;
pub const SELF_TEST_NONE                  : u64 = 0x0000000000000000;
pub const SELF_TEST_RUNNING               : u64 = 0x0000000000000002;
pub const SELF_TEST_PASS                  : u64 = 0x0000000000000004;
pub const SELF_TEST_FAIL                  : u64 = 0x0000000000000006;

// RECEIVER : 2-bit field  bits 3-4
pub const RECEIVER_MASK                   : u64 = 0x0000000000000018;
pub const RECEIVER_SHIFT                  : u64 = 0x0000000000000003;
pub const RECEIVER_OFF                    : u64 = 0x0000000000000000;
pub const RECEIVER_IDLE                   : u64 = 0x0000000000000008;
pub const RECEIVER_TUNING                 : u64 = 0x0000000000000010;
pub const RECEIVER_LOCKED                 : u64 = 0x0000000000000018;

// SCAN_MODE : 2-bit field  bits 5-6
pub const SCAN_MODE_MASK                  : u64 = 0x0000000000000060;
pub const SCAN_MODE_SHIFT                 : u64 = 0x0000000000000005;
pub const SCAN_MODE_NONE                  : u64 = 0x0000000000000000;
pub const SCAN_MODE_WIDEBAND              : u64 = 0x0000000000000020;
pub const SCAN_MODE_NARROWBAND            : u64 = 0x0000000000000040;
pub const SCAN_MODE_ADAPTIVE              : u64 = 0x0000000000000060;

// GAIN_CAL : 1-bit field  bits 7-7
pub const GAIN_CAL_MASK                   : u64 = 0x0000000000000080;
pub const GAIN_CAL_SHIFT                  : u64 = 0x0000000000000007;
pub const GAIN_CAL_NO                     : u64 = 0x0000000000000000;
pub const GAIN_CAL_YES                    : u64 = 0x0000000000000080;

// SIGNAL_DET : 2-bit field  bits 8-9
pub const SIGNAL_DET_MASK                 : u64 = 0x0000000000000300;
pub const SIGNAL_DET_SHIFT                : u64 = 0x0000000000000008;
pub const SIGNAL_DET_NONE                 : u64 = 0x0000000000000000;
pub const SIGNAL_DET_CANDIDATE            : u64 = 0x0000000000000100;
pub const SIGNAL_DET_CONFIRMED            : u64 = 0x0000000000000200;
pub const SIGNAL_DET_CLASSIFIED           : u64 = 0x0000000000000300;

// FREQ_ANALYSIS : 2-bit field  bits 10-11
pub const FREQ_ANALYSIS_MASK              : u64 = 0x0000000000000C00;
pub const FREQ_ANALYSIS_SHIFT             : u64 = 0x000000000000000A;
pub const FREQ_ANALYSIS_NONE              : u64 = 0x0000000000000000;
pub const FREQ_ANALYSIS_COARSE            : u64 = 0x0000000000000400;
pub const FREQ_ANALYSIS_FINE              : u64 = 0x0000000000000800;
pub const FREQ_ANALYSIS_COMPLETE          : u64 = 0x0000000000000C00;

// AOA : 2-bit field  bits 12-13
pub const AOA_MASK                        : u64 = 0x0000000000003000;
pub const AOA_SHIFT                       : u64 = 0x000000000000000C;
pub const AOA_NONE                        : u64 = 0x0000000000000000;
pub const AOA_MEASURING                   : u64 = 0x0000000000001000;
pub const AOA_SINGLE                      : u64 = 0x0000000000002000;
pub const AOA_MULTI                       : u64 = 0x0000000000003000;

// TDOA : 2-bit field  bits 14-15
pub const TDOA_MASK                       : u64 = 0x000000000000C000;
pub const TDOA_SHIFT                      : u64 = 0x000000000000000E;
pub const TDOA_NONE                       : u64 = 0x0000000000000000;
pub const TDOA_SYNC                       : u64 = 0x0000000000004000;
pub const TDOA_MEASURED                   : u64 = 0x0000000000008000;
pub const TDOA_RESOLVED                   : u64 = 0x000000000000C000;

// INTERFERENCE : 2-bit field  bits 16-17
pub const INTERFERENCE_MASK               : u64 = 0x0000000000030000;
pub const INTERFERENCE_SHIFT              : u64 = 0x0000000000000010;
pub const INTERFERENCE_NONE               : u64 = 0x0000000000000000;
pub const INTERFERENCE_DETECTED           : u64 = 0x0000000000010000;
pub const INTERFERENCE_CHARACTERISED      : u64 = 0x0000000000020000;
pub const INTERFERENCE_MITIGATED          : u64 = 0x0000000000030000;

// JAMMING : 2-bit field  bits 18-19
pub const JAMMING_MASK                    : u64 = 0x00000000000C0000;
pub const JAMMING_SHIFT                   : u64 = 0x0000000000000012;
pub const JAMMING_NONE                    : u64 = 0x0000000000000000;
pub const JAMMING_SUSPECTED               : u64 = 0x0000000000040000;
pub const JAMMING_CONFIRMED               : u64 = 0x0000000000080000;
pub const JAMMING_COUNTERED               : u64 = 0x00000000000C0000;

// MITIGATION : 1-bit field  bits 20-20
pub const MITIGATION_MASK                 : u64 = 0x0000000000100000;
pub const MITIGATION_SHIFT                : u64 = 0x0000000000000014;
pub const MITIGATION_INACTIVE             : u64 = 0x0000000000000000;
pub const MITIGATION_ACTIVE               : u64 = 0x0000000000100000;

// FIX : 2-bit field  bits 22-23
pub const FIX_MASK                        : u64 = 0x0000000000C00000;
pub const FIX_SHIFT                       : u64 = 0x0000000000000016;
pub const FIX_NONE                        : u64 = 0x0000000000000000;
pub const FIX_COARSE                      : u64 = 0x0000000000400000;
pub const FIX_REFINED                     : u64 = 0x0000000000800000;
pub const FIX_FUSED                       : u64 = 0x0000000000C00000;

// CONFIDENCE : 2-bit field  bits 24-25
pub const CONFIDENCE_MASK                 : u64 = 0x0000000003000000;
pub const CONFIDENCE_SHIFT                : u64 = 0x0000000000000018;
pub const CONFIDENCE_NONE                 : u64 = 0x0000000000000000;
pub const CONFIDENCE_LOW                  : u64 = 0x0000000001000000;
pub const CONFIDENCE_MEDIUM               : u64 = 0x0000000002000000;
pub const CONFIDENCE_HIGH                 : u64 = 0x0000000003000000;

// REPORT_READY : 1-bit field  bits 26-26
pub const REPORT_READY_MASK               : u64 = 0x0000000004000000;
pub const REPORT_READY_SHIFT              : u64 = 0x000000000000001A;
pub const REPORT_READY_NO                 : u64 = 0x0000000000000000;
pub const REPORT_READY_YES                : u64 = 0x0000000004000000;

// BDA : 1-bit field  bits 27-27
pub const BDA_MASK                        : u64 = 0x0000000008000000;
pub const BDA_SHIFT                       : u64 = 0x000000000000001B;
pub const BDA_NONE                        : u64 = 0x0000000000000000;
pub const BDA_COMPLETE                    : u64 = 0x0000000008000000;

// REPORT : 2-bit field  bits 28-29
pub const REPORT_MASK                     : u64 = 0x0000000030000000;
pub const REPORT_SHIFT                    : u64 = 0x000000000000001C;
pub const REPORT_NONE                     : u64 = 0x0000000000000000;
pub const REPORT_DRAFT                    : u64 = 0x0000000010000000;
pub const REPORT_FINAL                    : u64 = 0x0000000020000000;
pub const REPORT_TRANSMITTED              : u64 = 0x0000000030000000;

// ============================================================
// ACTIONS  (62 total)
// ============================================================

pub const ACTIONS : [Action; 62] = [
    // Power on the ELS payload
    Action {
        name                    : "Sys_PowerOn",
        pre_mask                : 0x00000001,
        pre_value               : 0x00000000,
        effect_mask             : 0x00000001,
        effect_value            : 0x00000001,
        cost                    : 1
    },
    // Start built-in self test
    Action {
        name                    : "Sys_RunSelfTest",
        pre_mask                : 0x00000007,
        pre_value               : 0x00000001,
        effect_mask             : 0x00000006,
        effect_value            : 0x00000002,
        cost                    : 2
    },
    // Self test completes successfully
    Action {
        name                    : "Sys_SelfTestPass",
        pre_mask                : 0x00000006,
        pre_value               : 0x00000002,
        effect_mask             : 0x00000006,
        effect_value            : 0x00000004,
        cost                    : 1
    },
    // Self test fails
    Action {
        name                    : "Sys_SelfTestFail",
        pre_mask                : 0x00000006,
        pre_value               : 0x00000002,
        effect_mask             : 0x00000006,
        effect_value            : 0x00000006,
        cost                    : 1
    },
    // Reset after failure for retry
    Action {
        name                    : "Sys_RetrySelfTest",
        pre_mask                : 0x00000006,
        pre_value               : 0x00000006,
        effect_mask             : 0x00000006,
        effect_value            : 0x00000000,
        cost                    : 3
    },
    // Warm reboot clears test state and gain cal
    Action {
        name                    : "Sys_WarmReboot",
        pre_mask                : 0x00000007,
        pre_value               : 0x00000007,
        effect_mask             : 0x00000086,
        effect_value            : 0x00000000,
        cost                    : 4
    },
    // Bring receiver from OFF to IDLE
    Action {
        name                    : "RF_ActivateReceiver",
        pre_mask                : 0x0000001F,
        pre_value               : 0x00000005,
        effect_mask             : 0x00000018,
        effect_value            : 0x00000008,
        cost                    : 2
    },
    // Calibrate receiver gain
    Action {
        name                    : "RF_CalibrateGain",
        pre_mask                : 0x00000098,
        pre_value               : 0x00000008,
        effect_mask             : 0x00000080,
        effect_value            : 0x00000080,
        cost                    : 3
    },
    // Select wideband scan mode
    Action {
        name                    : "RF_SetWideband",
        pre_mask                : 0x00000078,
        pre_value               : 0x00000008,
        effect_mask             : 0x00000060,
        effect_value            : 0x00000020,
        cost                    : 2
    },
    // Select narrowband scan mode
    Action {
        name                    : "RF_SetNarrowband",
        pre_mask                : 0x00000078,
        pre_value               : 0x00000008,
        effect_mask             : 0x00000060,
        effect_value            : 0x00000040,
        cost                    : 2
    },
    // Select adaptive scan (requires gain cal)
    Action {
        name                    : "RF_SetAdaptive",
        pre_mask                : 0x000000F8,
        pre_value               : 0x00000088,
        effect_mask             : 0x00000060,
        effect_value            : 0x00000060,
        cost                    : 3
    },
    // Narrow down from wideband sweep
    Action {
        name                    : "RF_NarrowFromWide",
        pre_mask                : 0x00000060,
        pre_value               : 0x00000020,
        effect_mask             : 0x00000060,
        effect_value            : 0x00000040,
        cost                    : 1
    },
    // Begin receiver tuning
    Action {
        name                    : "RF_StartTuning",
        pre_mask                : 0x00000018,
        pre_value               : 0x00000008,
        effect_mask             : 0x00000018,
        effect_value            : 0x00000010,
        cost                    : 2
    },
    // Lock receiver onto target frequency
    Action {
        name                    : "RF_LockReceiver",
        pre_mask                : 0x00000018,
        pre_value               : 0x00000010,
        effect_mask             : 0x00000018,
        effect_value            : 0x00000018,
        cost                    : 3
    },
    // Re-tune for frequency hopping
    Action {
        name                    : "RF_Retune",
        pre_mask                : 0x00000018,
        pre_value               : 0x00000018,
        effect_mask             : 0x00000018,
        effect_value            : 0x00000010,
        cost                    : 2
    },
    // Recalibrate gain during tuning (idempotent)
    Action {
        name                    : "RF_RecalibrateGain",
        pre_mask                : 0x00000098,
        pre_value               : 0x00000090,
        effect_mask             : 0x00000080,
        effect_value            : 0x00000080,
        cost                    : 2
    },
    // Upgrade to adaptive mode from narrowband
    Action {
        name                    : "RF_AdaptiveFromNarrow",
        pre_mask                : 0x000000F8,
        pre_value               : 0x000000C8,
        effect_mask             : 0x00000060,
        effect_value            : 0x00000060,
        cost                    : 2
    },
    // Detect a candidate emitter signal
    Action {
        name                    : "Sig_DetectCandidate",
        pre_mask                : 0x00000318,
        pre_value               : 0x00000018,
        effect_mask             : 0x00000300,
        effect_value            : 0x00000100,
        cost                    : 4
    },
    // Confirm candidate as real emitter
    Action {
        name                    : "Sig_ConfirmSignal",
        pre_mask                : 0x00000300,
        pre_value               : 0x00000100,
        effect_mask             : 0x00000300,
        effect_value            : 0x00000200,
        cost                    : 3
    },
    // Classify emitter type
    Action {
        name                    : "Sig_ClassifyEmitter",
        pre_mask                : 0x00000300,
        pre_value               : 0x00000200,
        effect_mask             : 0x00000300,
        effect_value            : 0x00000300,
        cost                    : 5
    },
    // Re-classify with full freq data
    Action {
        name                    : "Sig_ReclassifyEmitter",
        pre_mask                : 0x00000F00,
        pre_value               : 0x00000F00,
        effect_mask             : 0x00000300,
        effect_value            : 0x00000300,
        cost                    : 3
    },
    // Coarse frequency analysis on confirmed signal
    Action {
        name                    : "Freq_CoarseAnalysis",
        pre_mask                : 0x00000F00,
        pre_value               : 0x00000200,
        effect_mask             : 0x00000C00,
        effect_value            : 0x00000400,
        cost                    : 3
    },
    // Coarse analysis — cheaper when already classified
    Action {
        name                    : "Freq_CoarseFromClassified",
        pre_mask                : 0x00000F00,
        pre_value               : 0x00000300,
        effect_mask             : 0x00000C00,
        effect_value            : 0x00000400,
        cost                    : 2
    },
    // Fine frequency analysis using narrowband
    Action {
        name                    : "Freq_FineAnalysis_NB",
        pre_mask                : 0x00000C60,
        pre_value               : 0x00000440,
        effect_mask             : 0x00000C00,
        effect_value            : 0x00000800,
        cost                    : 5
    },
    // Fine frequency analysis using adaptive mode
    Action {
        name                    : "Freq_FineAnalysis_Adapt",
        pre_mask                : 0x00000C60,
        pre_value               : 0x00000460,
        effect_mask             : 0x00000C00,
        effect_value            : 0x00000800,
        cost                    : 3
    },
    // Complete frequency analysis
    Action {
        name                    : "Freq_Complete",
        pre_mask                : 0x00000C00,
        pre_value               : 0x00000800,
        effect_mask             : 0x00000C00,
        effect_value            : 0x00000C00,
        cost                    : 4
    },
    // Start AOA measurement on confirmed signal
    Action {
        name                    : "AOA_StartMeasurement",
        pre_mask                : 0x00003318,
        pre_value               : 0x00000218,
        effect_mask             : 0x00003000,
        effect_value            : 0x00001000,
        cost                    : 4
    },
    // Start AOA from classified emitter
    Action {
        name                    : "AOA_StartFromClassified",
        pre_mask                : 0x00003318,
        pre_value               : 0x00000318,
        effect_mask             : 0x00003000,
        effect_value            : 0x00001000,
        cost                    : 3
    },
    // Obtain single AOA bearing
    Action {
        name                    : "AOA_SingleBearing",
        pre_mask                : 0x00003000,
        pre_value               : 0x00001000,
        effect_mask             : 0x00003000,
        effect_value            : 0x00002000,
        cost                    : 3
    },
    // Accumulate multiple bearings for better accuracy
    Action {
        name                    : "AOA_MultiBearing",
        pre_mask                : 0x00003080,
        pre_value               : 0x00002080,
        effect_mask             : 0x00003000,
        effect_value            : 0x00003000,
        cost                    : 6
    },
    // Refine single bearing using complete freq data
    Action {
        name                    : "AOA_RefineBearing",
        pre_mask                : 0x00003C00,
        pre_value               : 0x00002C00,
        effect_mask             : 0x00003000,
        effect_value            : 0x00003000,
        cost                    : 4
    },
    // Synchronise time reference for TDOA
    Action {
        name                    : "TDOA_TimeSync",
        pre_mask                : 0x0000C318,
        pre_value               : 0x00000218,
        effect_mask             : 0x0000C000,
        effect_value            : 0x00004000,
        cost                    : 5
    },
    // Take TDOA measurement
    Action {
        name                    : "TDOA_Measure",
        pre_mask                : 0x0000C000,
        pre_value               : 0x00004000,
        effect_mask             : 0x0000C000,
        effect_value            : 0x00008000,
        cost                    : 6
    },
    // Resolve TDOA ambiguity
    Action {
        name                    : "TDOA_Resolve",
        pre_mask                : 0x0000CC00,
        pre_value               : 0x00008400,
        effect_mask             : 0x0000C000,
        effect_value            : 0x0000C000,
        cost                    : 5
    },
    // Resolve TDOA with fine freq — cheaper
    Action {
        name                    : "TDOA_ResolveFineLock",
        pre_mask                : 0x0000CC00,
        pre_value               : 0x00008800,
        effect_mask             : 0x0000C000,
        effect_value            : 0x0000C000,
        cost                    : 3
    },
    // Detect RF interference
    Action {
        name                    : "Intf_Detect",
        pre_mask                : 0x00030018,
        pre_value               : 0x00000018,
        effect_mask             : 0x00030000,
        effect_value            : 0x00010000,
        cost                    : 3
    },
    // Characterise interference source
    Action {
        name                    : "Intf_Characterise",
        pre_mask                : 0x00030C00,
        pre_value               : 0x00010400,
        effect_mask             : 0x00030000,
        effect_value            : 0x00020000,
        cost                    : 5
    },
    // Apply notch filter / null steering
    Action {
        name                    : "Intf_Mitigate",
        pre_mask                : 0x00030000,
        pre_value               : 0x00020000,
        effect_mask             : 0x00130000,
        effect_value            : 0x00130000,
        cost                    : 6
    },
    // Adaptive mitigation — cheaper with adaptive scan
    Action {
        name                    : "Intf_MitigateAdaptive",
        pre_mask                : 0x00030060,
        pre_value               : 0x00020060,
        effect_mask             : 0x00130000,
        effect_value            : 0x00130000,
        cost                    : 4
    },
    // Flag suspected jamming from interference data
    Action {
        name                    : "Jam_Suspect",
        pre_mask                : 0x000F0000,
        pre_value               : 0x00020000,
        effect_mask             : 0x000C0000,
        effect_value            : 0x00040000,
        cost                    : 2
    },
    // Confirm jamming with fine frequency analysis
    Action {
        name                    : "Jam_Confirm",
        pre_mask                : 0x000C0C00,
        pre_value               : 0x00040800,
        effect_mask             : 0x000C0000,
        effect_value            : 0x00080000,
        cost                    : 4
    },
    // Confirm jamming with complete freq data — cheaper
    Action {
        name                    : "Jam_ConfirmFromComplete",
        pre_mask                : 0x000C0C00,
        pre_value               : 0x00040C00,
        effect_mask             : 0x000C0000,
        effect_value            : 0x00080000,
        cost                    : 3
    },
    // Counter jamming via frequency hopping
    Action {
        name                    : "Jam_CounterHop",
        pre_mask                : 0x000C0060,
        pre_value               : 0x00080060,
        effect_mask             : 0x000C0000,
        effect_value            : 0x000C0000,
        cost                    : 8
    },
    // Counter jamming via notch filter
    Action {
        name                    : "Jam_CounterNotch",
        pre_mask                : 0x001C0000,
        pre_value               : 0x00180000,
        effect_mask             : 0x000C0000,
        effect_value            : 0x000C0000,
        cost                    : 10
    },
    // Counter with spread-spectrum — needs adaptive + calibrated gain
    Action {
        name                    : "Jam_CounterSpread",
        pre_mask                : 0x000C00E0,
        pre_value               : 0x000800E0,
        effect_mask             : 0x001C0000,
        effect_value            : 0x001C0000,
        cost                    : 7
    },
    // Skip interference path — clean RF environment
    Action {
        name                    : "Intf_SkipClean",
        pre_mask                : 0x000F0018,
        pre_value               : 0x00000018,
        effect_mask             : 0x001F0000,
        effect_value            : 0x001F0000,
        cost                    : 0
    },
    // Coarse fix from single AOA bearing
    Action {
        name                    : "Fix_CoarseAOA",
        pre_mask                : 0x00C03000,
        pre_value               : 0x00002000,
        effect_mask             : 0x03C00000,
        effect_value            : 0x01400000,
        cost                    : 3
    },
    // Coarse fix from TDOA measurement
    Action {
        name                    : "Fix_CoarseTDOA",
        pre_mask                : 0x00C0C000,
        pre_value               : 0x00008000,
        effect_mask             : 0x03C00000,
        effect_value            : 0x01400000,
        cost                    : 3
    },
    // Refined fix from multi-bearing AOA
    Action {
        name                    : "Fix_RefinedAOA",
        pre_mask                : 0x00C03000,
        pre_value               : 0x00403000,
        effect_mask             : 0x03C00000,
        effect_value            : 0x02800000,
        cost                    : 4
    },
    // Refined fix from resolved TDOA
    Action {
        name                    : "Fix_RefinedTDOA",
        pre_mask                : 0x00C0C000,
        pre_value               : 0x0040C000,
        effect_mask             : 0x03C00000,
        effect_value            : 0x02800000,
        cost                    : 4
    },
    // Fuse AOA + TDOA for optimal fix
    Action {
        name                    : "Fix_FuseAOA_TDOA",
        pre_mask                : 0x00C0F000,
        pre_value               : 0x0080F000,
        effect_mask             : 0x03C00000,
        effect_value            : 0x03C00000,
        cost                    : 5
    },
    // Fuse from AOA-only path (medium confidence)
    Action {
        name                    : "Fix_FuseAOAOnly",
        pre_mask                : 0x00C03C00,
        pre_value               : 0x00803C00,
        effect_mask             : 0x03C00000,
        effect_value            : 0x02C00000,
        cost                    : 6
    },
    // Fuse from TDOA-only path (medium confidence)
    Action {
        name                    : "Fix_FuseTDOAOnly",
        pre_mask                : 0x00C0CC00,
        pre_value               : 0x0080CC00,
        effect_mask             : 0x03C00000,
        effect_value            : 0x02C00000,
        cost                    : 6
    },
    // Upgrade coarse fix using complete freq data
    Action {
        name                    : "Fix_RefineWithFreq",
        pre_mask                : 0x03C00C00,
        pre_value               : 0x01400C00,
        effect_mask             : 0x03C00000,
        effect_value            : 0x02800000,
        cost                    : 3
    },
    // Upgrade confidence to HIGH using classified emitter data
    Action {
        name                    : "Fix_UpgradeConfidence",
        pre_mask                : 0x03C00300,
        pre_value               : 0x02C00300,
        effect_mask             : 0x03000000,
        effect_value            : 0x03000000,
        cost                    : 2
    },
    // Prepare report once fused fix is available
    Action {
        name                    : "Rpt_PrepareReport",
        pre_mask                : 0x04C00000,
        pre_value               : 0x00C00000,
        effect_mask             : 0x04000000,
        effect_value            : 0x04000000,
        cost                    : 2
    },
    // Run Battle Damage Assessment
    Action {
        name                    : "Rpt_BDA",
        pre_mask                : 0x0C000300,
        pre_value               : 0x04000300,
        effect_mask             : 0x08000000,
        effect_value            : 0x08000000,
        cost                    : 4
    },
    // Draft the mission report
    Action {
        name                    : "Rpt_Draft",
        pre_mask                : 0x34000000,
        pre_value               : 0x04000000,
        effect_mask             : 0x30000000,
        effect_value            : 0x10000000,
        cost                    : 2
    },
    // Finalise report (requires BDA)
    Action {
        name                    : "Rpt_Finalise",
        pre_mask                : 0x38000000,
        pre_value               : 0x18000000,
        effect_mask             : 0x30000000,
        effect_value            : 0x20000000,
        cost                    : 3
    },
    // Transmit final report
    Action {
        name                    : "Rpt_Transmit",
        pre_mask                : 0x30000000,
        pre_value               : 0x20000000,
        effect_mask             : 0x30000000,
        effect_value            : 0x30000000,
        cost                    : 2
    },
    // Draft report without BDA (degraded mode)
    Action {
        name                    : "Rpt_DraftWithoutBDA",
        pre_mask                : 0x34C00000,
        pre_value               : 0x04C00000,
        effect_mask             : 0x30000000,
        effect_value            : 0x10000000,
        cost                    : 3
    },
    // Finalise without BDA if confidence is HIGH
    Action {
        name                    : "Rpt_FinaliseWithoutBDA",
        pre_mask                : 0x33000000,
        pre_value               : 0x13000000,
        effect_mask             : 0x30000000,
        effect_value            : 0x20000000,
        cost                    : 4
    },
];

/*
┌────────────────────────────────────────────────────────────────────┐
│  BIT LAYOUT  (29 bits used of 64 available)
├────────────────────────────────────────────────────────────────────┤
│  Bits  0- 0 : POWER        (1 bit )  [OFF, ON]
│  Bits  1- 2 : SELF_TEST    (2 bits)  [NONE, RUNNING, PASS, FAIL]
│  Bits  3- 4 : RECEIVER     (2 bits)  [OFF, IDLE, TUNING, LOCKED]
│  Bits  5- 6 : SCAN_MODE    (2 bits)  [NONE, WIDEBAND, NARROWBAND, ADAPTIVE]
│  Bits  7- 7 : GAIN_CAL     (1 bit )  [NO, YES]
│  Bits  8- 9 : SIGNAL_DET   (2 bits)  [NONE, CANDIDATE, CONFIRMED, CLASSIFIED]
│  Bits 10-11 : FREQ_ANALYSIS (2 bits)  [NONE, COARSE, FINE, COMPLETE]
│  Bits 12-13 : AOA          (2 bits)  [NONE, MEASURING, SINGLE, MULTI]
│  Bits 14-15 : TDOA         (2 bits)  [NONE, SYNC, MEASURED, RESOLVED]
│  Bits 16-17 : INTERFERENCE (2 bits)  [NONE, DETECTED, CHARACTERISED, MITIGATED]
│  Bits 18-19 : JAMMING      (2 bits)  [NONE, SUSPECTED, CONFIRMED, COUNTERED]
│  Bits 20-20 : MITIGATION   (1 bit )  [INACTIVE, ACTIVE]
│  Bits 22-23 : FIX          (2 bits)  [NONE, COARSE, REFINED, FUSED]
│  Bits 24-25 : CONFIDENCE   (2 bits)  [NONE, LOW, MEDIUM, HIGH]
│  Bits 26-26 : REPORT_READY (1 bit )  [NO, YES]
│  Bits 27-27 : BDA          (1 bit )  [NONE, COMPLETE]
│  Bits 28-29 : REPORT       (2 bits)  [NONE, DRAFT, FINAL, TRANSMITTED]
└────────────────────────────────────────────────────────────────────┘
*/
